# Generated by Django 3.2.4 on 2021-12-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0005_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Recruiter', 'Recruiter'), ('Applicant', 'Applicant')], default='Applicant', max_length=10),
        ),
    ]
