# Generated by Django 3.1.1 on 2022-03-20 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.DecimalField(decimal_places=8, max_digits=10)),
                ('application_date_time', models.DateTimeField()),
                ('application_status', models.CharField(choices=[('S', 'selected'), ('R', 'in_review'), ('W', 'Waitlist')], default='W', max_length=2)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicantdetails')),
            ],
        ),
    ]
