# Generated by Django 3.2.4 on 2022-03-16 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_applicant', '0002_applicantdetails_applicant_id'),
        ('core_job_posts', '0002_jobposts_recruiter_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgpa', models.DecimalField(decimal_places=8, max_digits=10)),
                ('application_date_time', models.DateTimeField()),
                ('application_status', models.CharField(choices=[('S', 'selected'), ('R', 'in_review'), ('W', 'Waitlist')], default='W', max_length=2)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_applicant.applicantdetails')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_job_posts.jobposts')),
            ],
        ),
    ]
