# Generated by Django 3.2.4 on 2022-03-17 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_applications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationsdetails',
            old_name='cgpa',
            new_name='similarity_score',
        ),
    ]
