# Generated by Django 3.1.1 on 2022-04-03 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('job_posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsdetails',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_posts.jobposts'),
        ),
    ]
