# Generated by Django 3.1.1 on 2022-03-31 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_applicationsdetails_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsdetails',
            name='annotated_resume_filename',
            field=models.CharField(default=None, max_length=10485760, null=True),
        ),
    ]
