# Generated by Django 3.1.1 on 2022-05-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_applicationsdetails_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationsdetails',
            name='years_of_experience',
            field=models.IntegerField(null=True),
        ),
    ]
