# Generated by Django 3.2.4 on 2022-03-15 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_recruiter', '0002_auto_20220315_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_description', models.TextField(max_length=500)),
                ('location', models.CharField(max_length=200)),
                ('no_of_openings', models.IntegerField()),
                ('application_deadline', models.DateTimeField()),
                ('skills_required', models.TextField(max_length=1000)),
                ('recruiter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core_recruiter.recruiterdetails')),
            ],
        ),
    ]
