# Generated by Django 3.2.4 on 2022-03-15 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_job_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposts',
            name='application_deadline',
            field=models.DateField(),
        ),
    ]
