# Generated by Django 3.1.1 on 2022-03-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposts',
            name='job_description',
            field=models.TextField(max_length=5000),
        ),
    ]
