# Generated by Django 3.1.1 on 2022-05-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposts',
            name='weightage',
            field=models.IntegerField(null=True),
        ),
    ]
