# Generated by Django 3.2.4 on 2022-03-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_job_posts', '0002_jobposts_recruiter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposts',
            name='parsed_job_description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
