# Generated by Django 3.2.4 on 2022-03-16 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='uploads/')),
                ('preferred_location', models.CharField(choices=[('CA', 'California'), ('NYC', 'New York City'), ('IL', 'Chicago'), ('WS', 'Seattle'), ('BO', 'Boulder')], default='CA', max_length=50)),
                ('job_categories', models.CharField(choices=[('SWE', 'Software Engineer'), ('FE', 'Frontend Engineer'), ('BE', 'Backend Engineering'), ('D', 'Devops'), ('ML', 'Machine Learning Engineer')], default='SWE', max_length=3)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
