# Generated by Django 4.0.3 on 2022-05-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_categories', models.CharField(choices=[('EN', 'Engineering'), ('SA', 'Sales'), ('BU', 'Business'), ('ET', 'Entertainment'), ('F', 'Food'), ('O', 'Other')], default='EN', max_length=3)),
            ],
        ),
    ]
