# Generated by Django 3.2.4 on 2022-03-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterdetails',
            name='company_description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='recruiterdetails',
            name='corporate_address',
            field=models.TextField(max_length=1000),
        ),
    ]
